title: Michael Fusco | Chief-Prince-Of-Function
email: chief.prince.of.function@gmail.com
description: >-
  Veteran, builder, nonprofit founder, and aspiring full-stack developer creating useful things with purpose.
baseurl: ""
url: ""
twitter_username: fuscaha
github_username: Chief-Prince-Of-Function

# Optional: add /assets/images/favicon.png once you create it.
favicon: /assets/images/favicon.png

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
